### ISSUE TITLE
Publish sdist tarballs on pypi

### ISSUE THREAD

**Issue by toabctl** [containers/python-podman#32]
Currently only wheels are published on pypi (see https://pypi.org/project/podman/#files ).
But distros might want to build from an sdist tarball so please publish that in addition to the current .whl file.

**Comment by rhatdan** [comment]
Could you open a PR to make this happen?

**Comment by toabctl** [comment]
> Could you open a PR to make this happen?

@rhatdan what's the process publishing on pypi? I don't find anything automated in this repo. So I assume you did that manually (with `twine` or so?)?
It's possible to automatically publish via travis (see https://docs.travis-ci.com/user/deployment/pypi/) but looks like you are not using travis yet.
So what's the way going forward?

**Comment by rhatdan** [comment]
I don't know, I am hoping others explain it, since I am in the dark for the entire process.
@saschagrunert @cevich @jwhonce @vrothberg @baude Any ideas?

**Comment by rhatdan** [comment]
@jnovy is this something you could help with?

**Comment by saschagrunert** [comment]
It looks like that the repo gets automatically deployed on tags:
https://github.com/containers/python-podman/blob/508376ecf16636bd4d6badb0d70977c453888d4a/.travis.yml#L17-L24

**Comment by rhatdan** [comment]
So create a new tag and we are golden.

**Comment by rhatdan** [comment]
I tagged and released v0.0.1 version of this, hopefully this triggers a push to pypy so people can use it.

**Comment by rhatdan** [comment]
@saschagrunert Failed to deploy.
https://travis-ci.org/containers/python-podman/jobs/551830753
@jwhonce Any ideas?

**Comment by toabctl** [comment]
> I tagged and released v0.0.1 version of this, hopefully this triggers a push to pypy so people can use it.

eh - pypi has already version 0.11.1.1 . So tagging 0.0.1 seem to be wrong.

**Comment by toabctl** [comment]
I guess switching to `pbr` or `setuptools_scm` makes sense here.

**Comment by 4383** [comment]
>> > I tagged and released v0.0.1 version of this, hopefully this triggers a push to pypy so people can use it.
>> 
>> eh - pypi has already version 0.11.1.1 . So tagging 0.0.1 seem to be wrong.

> I guess switching to `pbr` or `setuptools_scm` makes sense here. 

Hey,

@toabctl: I'm not sure to see the gain to switch from `pbr` to `setuptools_scm` here, why?

The issue here is that something went wrong in the `README.md` and pypi try to convert it to the rst format and fail... I've submit a fix #37 to reintroduce the `long_description_content_type` config.

travis trigger deployments on pypi when we push a new `git tag`, `pbr` is used to generate the version automatically based on the pushed `git tag`. pbr is not an issue here, tagging to `0.0.1` is not an issue too, you can create new version inferior to an existing and already published version (cf. the openstack releases https://github.com/openstack/releases/commits/master).

**Comment by 4383** [comment]
openstack have the same issue:

http://lists.openstack.org/pipermail/openstack-discuss/2019-July/007459.html, I don't think that this is a podman issue...

**Comment by 4383** [comment]
> > Could you open a PR to make this happen?
> 
> @rhatdan what's the process publishing on pypi? I don't find anything automated in this repo. So I assume you did that manually (with `twine` or so?)?
> It's possible to automatically publish via travis (see https://docs.travis-ci.com/user/deployment/pypi/) but looks like you are not using travis yet.
> So what's the way going forward?

To be more clear on this topic it's already automated by using `pbr` and `deploy` on travis.

Also [we already trying to publish sdist](https://github.com/containers/python-podman/blob/master/.travis.yml#L24) on pypi by using some [travis deployment options](https://docs.travis-ci.com/user/deployment/pypi/#uploading-different-distributions). 

The main issue for the moment is the issue related to the rst format, but it's not a podman issue, we also have the same issue on openstack... (cf. my previous comment)

**Comment by 4383** [comment]
Well... I think the issue here is related to:
- https://github.com/pypa/warehouse/pull/5835
- https://github.com/pypa/warehouse/issues/5890

**Comment by jwhonce** [comment]
@toabctl 

> eh - pypi has already version 0.11.1.1 . So tagging 0.0.1 seem to be wrong.

We're discussing right now should the python-podman versions track with libpod, or should the python-podman versions remain a unique vector?
