### ISSUE TITLE
Newest version is "lower" than highest version on PyPi

### ISSUE THREAD

**Issue by h-vetinari** [containers/python-podman#43]
PyPI has a release 0.12.0, wherease the newest tag is 0.0.3; see also https://github.com/containers/python-podman/releases

This causes `pip install podman` to install 0.12.0 over the newer 0.0.3.

AFAIK (here's a [ref](https://doughellmann.com/blog/2016/02/25/so-youve-released-a-broken-package-to-pypi-what-do-you-do-now/)), it's not possible to retract a package from PyPI, so the only choice would be to start releasing 0.13 and upwards.

**Comment by rhatdan** [comment]
I am fine with bouncing it to 0.13.0 or 1.0.0

**Comment by jwhonce** [comment]
Resolved with version 1.6.0 as of 2019/10/11 https://pypi.org/project/podman/
