### ISSUE TITLE
clarify LICENSE situation

### ISSUE THREAD

**Issue by h-vetinari** [containers/python-podman#44]
Currently there are two license files (`LICENSE` & `LICENSE.txt`) which seem redundant. Podman [itself](https://github.com/containers/libpod) just uses one `LICENSE` file.

This should IMO be deduplicated.

**Comment by rhatdan** [comment]
Please open a PR to remove the second license.txt file.

**Comment by 4383** [comment]
@rhatdan already opened => #45

**Comment by 4383** [comment]
I think we can close this one (related changes #45)
